### PR TITLE
Flatten credentials v1 context and use 1.1 features.

### PR DESCRIPTION
**Pull request by dlongley**
This is *likely* what we want for the credentials-v1 context, @yancyribbens. However, I'm still testing against the test suite.

### CODE REVIEW

**Comment by yancyribbens** [comment]
@dlongley thanks!  I'll give it a test also offline if this is the solution.

**Comment by yancyribbens** [comment]
I can also update the [PR](https://github.com/w3c/vc-data-model/pull/587) with the updated `sha256` hash.

**Comment by dlongley** [comment]
@yancyribbens, I'd expect that the only difficulty you might run into is with extending contexts (e.g. the ODRL one in the test suite) that redefine terms to the same definitions ... I'm working through that bug w/the JSON-LD WG.

**Comment by yancyribbens** [comment]
@dlongley I'm having some issues loading this context:
```JSON::LD::JsonLdError::InvalidTermDefinition (invalid term definition: Term definition for "@protected" is an TrueClass on term "@protected")```

Any idea why?  Is this a problem with the library I'm using?

**Comment by dlongley** [comment]
@yancyribbens,

> Any idea why? Is this a problem with the library I'm using?

Yes, it sounds like whatever library you're using hasn't implemented protected terms yet:

https://www.w3.org/TR/json-ld11/#protected-term-definitions

**Comment by dlongley** [comment]
Ok, this context is ready to go.

**Comment by dlongley** [comment]
Ok, I added some backwards compatibility stuff -- I do think this should be pulled in now.

**Review by yancyribbens — APPROVED** [review]

**Pull request merged**
